GRANT CREATE SESSION TO TDM_CSAR_USER
/
GRANT CREATE SESSION TO TDM_IRISK_USER
/
GRANT CREATE SESSION TO TDM_MRT_USER
/
GRANT CREATE SESSION TO TDM_COMPL_USER
/
GRANT CREATE SESSION TO RSKCALC 
/
GRANT CREATE SESSION TO TDM_CASH_USER
/
GRANT CREATE SESSION TO TDM_CREST_USER 
/
